version: '3.8'

services:
  minio:
    image: elestio/minio:latest
    container_name: ocr-minio
    environment:
      - TZ=Asia/Jakarta
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - ocr-network

  postgres:
    image: postgres:18-alpine
    container_name: ocr-postgres
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS="-U postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ocr-network

  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Jakarta
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ocr-network

  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr-api-img
    container_name: ocr-api
    environment:
      - TZ=Asia/Jakarta
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - QUARKUS_PROFILE=dev
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - ocr-network

volumes:
  postgres_data:
  minio_data:
  redis_data:

networks:
  ocr-network:
    driver: bridge
